CREATE EXTERNAL TABLE profiles_bronze.people(
  person_id string, 
  full_name string, 
  first_name string, 
  middle_initial string, 
  middle_name string, 
  last_initial string, 
  last_name string, 
  sex string, 
  linkedin_url string, 
  linkedin_username string, 
  linkedin_id string, 
  facebook_url string, 
  facebook_username string, 
  facebook_id string, 
  twitter_url string, 
  twitter_username string, 
  github_url string, 
  github_username string, 
  industry string, 
  job_title string, 
  job_title_role string, 
  job_title_sub_role string, 
  job_title_class string, 
  job_title_levels string, 
  job_company_id string, 
  job_company_name string, 
  job_company_website string, 
  job_company_size string, 
  job_company_founded string, 
  job_company_industry string, 
  job_company_industry_v2 string, 
  job_company_linkedin_url string, 
  job_company_linkedin_id string, 
  job_company_facebook_url string, 
  job_company_twitter_url string, 
  job_company_location_name string, 
  job_company_location_locality string, 
  job_company_location_metro string, 
  job_company_location_region string, 
  job_company_location_geo string, 
  job_company_location_street_address string, 
  job_company_location_address_line_2 string, 
  job_company_location_postal_code string, 
  job_company_location_country string, 
  job_company_location_continent string, 
  job_last_changed string, 
  job_last_verified string, 
  job_start_date string, 
  location_country string, 
  location_continent string, 
  location_address_line_2 string, 
  location_last_updated string, 
  interests string, 
  skills string, 
  countries string, 
  dataset_version string, 
  birth_date string, 
  birth_year string, 
  emails string, 
  location_geo string, 
  location_locality string, 
  location_metro string, 
  location_name string, 
  location_names string, 
  location_postal_code string, 
  location_region string, 
  location_street_address string, 
  mobile_phone string, 
  personal_emails string, 
  phone_numbers string, 
  recommended_personal_email string, 
  regions string, 
  street_addresses string, 
  work_email string
)
PARTITIONED BY ( 
  date string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar'     = '"'
)
LOCATION
  's3://profiles-dev-345895787413-ap-southeast-1/bronze/people/'
TBLPROPERTIES (
  'skip.header.line.count'='1'
);

MSCK REPAIR TABLE profiles_bronze.people;
